server:
  port: 8080
  servlet:
    context-path: /hellfire
    session:
      timeout: 1200
    multipart:
      max-file-size: 30MB
      max-request-size: 5MB

verification:
  device:
    codeLength: 6
    #30天
    lifeSeconds: 2592000
    #5分钟
    codeLifeMilliseconds: 300000

spring:
  application:
    version: 0.0.1
    name: hellfire

  profiles:
    active: dev

  # redis Database Config
  redis:
    host: 127.0.0.1
    timeout: 3000

  # DataSource Config
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456

mybatis-plus:
  typeEnumsPackage: com.github.chenhao96.entity.enums
  global-config:
    db-config:
      logic-delete-field: logic
      logic-delete-value: 1
      logic-not-delete-value: 0