application:
  version: 0.0.1

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 60
    multipart:
      max-file-size: 30MB
      max-request-size: 5MB

spring:
  profiles:
    active: dev

  thymeleaf:
    mode: HTML5
    encoding: UTF-8

#  mobile:
#    devicedelegatingviewresolver:
#      enabled: true

  # redis Database Config
  redis:
    host: 127.0.0.1
    timeout: 3000

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456